# Generated by Django 5.0.9 on 2025-01-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerador',
            fields=[
                ('ID_Refrigerador', models.AutoField(primary_key=True, serialize=False)),
                ('DescripcionRef', models.CharField(max_length=150)),
                ('Min', models.FloatField(null=True)),
                ('Max', models.FloatField(null=True)),
                ('TipoRefrigerador', models.CharField(max_length=50, null=True)),
                ('SYNC', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Refrigerador',
                'verbose_name_plural': 'Refrigeradores',
                'db_table': 'Refrigeradores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TempEsterilizadores',
            fields=[
                ('ID_TempEsterilizador', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('TempC', models.FloatField()),
                ('TempF', models.FloatField()),
                ('ACorrectiva', models.CharField(blank=True, max_length=300, null=True)),
                ('APreventiva', models.CharField(blank=True, max_length=300, null=True)),
                ('Observaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('Inspecciono', models.IntegerField(db_column='Inspecciono')),
                ('Verifico', models.IntegerField(db_column='Verifico')),
                ('SYNC', models.BooleanField(default=False)),
                ('ID_Refrigerador', models.ForeignKey(db_column='ID_Refrigerador', null=True, on_delete=django.db.models.deletion.CASCADE, to='esterilizadores.refrigerador')),
            ],
            options={
                'verbose_name': 'Temperatura Esterilizador',
                'verbose_name_plural': 'Temperatura Esterilizadores',
                'db_table': 'TemperaturaEsterilizadores',
                'managed': True,
            },
        ),
    ]
