# Generated by Django 5.0.9 on 2025-01-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigeradores',
            fields=[
                ('ID_Refrigerador', models.AutoField(primary_key=True, serialize=False)),
                ('DescripcionRef', models.CharField(max_length=150)),
                ('Min', models.FloatField(null=True)),
                ('Max', models.FloatField(null=True)),
                ('TipoRefrigerador', models.CharField(max_length=50, null=True)),
                ('SYNC', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Refrigerador',
                'verbose_name_plural': 'Refrigeradores',
                'db_table': 'Refrigeradores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TemperaturaAreas',
            fields=[
                ('ID_TempAreas', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Hora', models.TimeField()),
                ('Temperatura', models.FloatField()),
                ('Comentarios', models.TextField(blank=True, null=True)),
                ('SYNC', models.BooleanField(default=False)),
                ('ID_Refrigerador', models.ForeignKey(db_column='ID_Refrigerador', null=True, on_delete=django.db.models.deletion.SET_NULL, to='temperature.refrigeradores')),
            ],
            options={
                'verbose_name': 'Temperatura Areas',
                'verbose_name_plural': 'Temperatura Areas',
                'db_table': 'TemperaturaAreas',
                'managed': True,
            },
        ),
    ]
